text = """clothing_dict = {
    "2": {"gender": "Unisex", "formality": "Casual", "type": "Top", "specific_type": "Casual"},
    "4": {"gender": "Womens", "formality": "Casual", "type": "Top", "specific_type": "Day Dresses"},
    "5": {"gender": "Womens", "formality": "Formal", "type": "Top", "specific_type": "Cocktail Dresses"},
    "6": {"gender": "Womens", "formality": "Formal", "type": "Top", "specific_type": "Gowns"},
    "7": {"gender": "Womens", "formality": "Casual", "type": "Bottom", "specific_type": "Skirts"},
    "8": {"gender": "Womens", "formality": "Casual", "type": "Bottom", "specific_type": "Mini Skirts"},
    "9": {"gender": "Womens", "formality": "Casual", "type": "Bottom", "specific_type": "Knee Length Skirts"},
    "10": {"gender": "Womens", "formality": "Casual", "type": "Bottom", "specific_type": "Long Skirts"},
    "11": {"gender": "Womens", "formality": "Casual", "type": "Top", "specific_type": "Tops"},
    "15": {"gender": "Womens", "formality": "Casual", "type": "Top", "specific_type": "Tunics"},
    "17": {"gender": "Womens", "formality": "Casual", "type": "Top", "specific_type": "Blouses"},
    "18": {"gender": "Unisex", "formality": "Casual", "type": "Top", "specific_type": "Cardigans", "occasion": "Casual"},
    "19": {"gender": "Womens", "formality": "Casual", "type": "Top", "specific_type": "Sweaters"},
    "21": {"gender": "Unisex", "formality": "Casual", "type": "Top", "specific_type": "T-Shirts"},
    "23": {"gender": "Unisex", "formality": "Casual", "type": "Top", "specific_type": "Outerwear"},
    "24": {"gender": "Unisex", "formality": "Casual", "type": "Top", "specific_type": "Coats"},
    "25": {"gender": "Unisex", "formality": "Casual", "type": "Top", "specific_type": "Jackets"},
    "26": {"gender": "Unisex", "formality": "Casual", "type": "Top", "specific_type": "Vests"},
    "27": {"gender": "Unisex", "formality": "Casual", "type": "Bottom", "specific_type": "Jeans"},
    "28": {"gender": "Unisex", "formality": "Casual", "type": "Bottom", "specific_type": "Pants"},
    "29": {"gender": "Unisex", "formality": "Casual", "type": "Bottom", "specific_type": "Shorts"},
    "30": {"gender": "Unisex", "formality": "Formal", "type": "Top", "specific_type": "Suits"},
    "31": {"gender": "Unisex", "formality": "Casual", "type": "Top", "specific_type": "Swimwear"},
    "33": {"gender": "Unisex", "formality": "Casual", "type": "Top", "specific_type": "Activewear"},
    "237": {"gender": "Unisex", "formality": "Casual", "type": "Bottom", "specific_type": "Skinny Jeans"},
    "238": {"gender": "Unisex", "formality": "Casual", "type": "Bottom", "specific_type": "Bootcut Jeans"},
    "239": {"gender": "Unisex", "formality": "Casual", "type": "Bottom", "specific_type": "Wide Leg Jeans"},
    "240": {"gender": "Unisex", "formality": "Casual", "type": "Bottom", "specific_type": "Boyfriend Jeans"},
    "241": {"gender": "Womens", "formality": "Casual", "type": "Bottom", "specific_type": "Leggings"},
    "243": {"gender": "Womens", "formality": "Casual", "type": "Top", "specific_type": "Jumpsuits"},
    "244": {"gender": "Womens", "formality": "Casual", "type": "Top", "specific_type": "Rompers"},
    "247": {"gender": "Womens", "formality": "Casual", "type": "Top", "specific_type": "Camisoles"},
    "248": {"gender": "Womens", "formality": "Casual", "type": "Top", "specific_type": "Chemises"},
    "249": {"gender": "Womens", "formality": "Casual", "type": "Top", "specific_type": "Pajamas"},
    "250": {"gender": "Womens", "formality": "Casual", "type": "Top", "specific_type": "Robes"},
    "251": {"gender": "Womens", "formality": "Casual", "type": "Bottom", "specific_type": "Tights"},
    "252": {"gender": "Unisex", "formality": "Casual", "type": "Top", "specific_type": "Activewear Tops"},
    "253": {"gender": "Unisex", "formality": "Casual", "type": "Bottom", "specific_type": "Activewear Pants"},
    "254": {"gender": "Unisex", "formality": "Casual", "type": "Bottom", "specific_type": "Activewear Skirts"},
    "255": {"gender": "Unisex", "formality": "Casual", "type": "Bottom", "specific_type": "Activewear Shorts"},
    "256": {"gender": "Unisex", "formality": "Casual", "type": "Top", "specific_type": "Activewear Jackets"},
    "257": {"gender": "Womens", "formality": "Casual", "type": "Top", "specific_type": "Sports Bras"},
    "271": {"gender": "Mens", "formality": "Casual", "type": "Top", "specific_type": "Clothing"},
    "272": {"gender": "Mens", "formality": "Casual", "type": "Top", "specific_type": "Shirts"},
    "273": {"gender": "Mens", "formality": "Casual", "type": "Top", "specific_type": "Sweaters"},
    "275": {"gender": "Mens", "formality": "Casual", "type": "Top", "specific_type": "T-Shirts"},
    "276": {"gender": "Mens", "formality": "Casual", "type": "Top", "specific_type": "Outerwear"},
    "277": {"gender": "Mens", "formality": "Casual", "type": "Top", "specific_type": "Sportcoats & Blazers"},
    "278": {"gender": "Mens", "formality": "Casual", "type": "Bottom", "specific_type": "Jeans"},
    "279": {"gender": "Mens", "formality": "Casual", "type": "Bottom", "specific_type": "Pants"},
    "280": {"gender": "Mens", "formality": "Casual", "type": "Bottom", "specific_type": "Shorts"},
    "281": {"gender": "Mens", "formality": "Formal", "type": "Top", "specific_type": "Suits"},
    "282": {"gender": "Mens", "formality": "Casual", "type": "Top", "specific_type": "Swimwear"},
    "283": {"gender": "Mens", "formality": "Casual", "type": "Top", "specific_type": "Underwear"},
    "284": {"gender": "Mens", "formality": "Casual", "type": "Top", "specific_type": "Sleepwear"},
    "285": {"gender": "Mens", "formality": "Casual", "type": "Top", "specific_type": "Activewear"},
    "286": {"gender": "Mens", "formality": "Casual", "type": "Top", "specific_type": "Activewear Tops"},
    "287": {"gender": "Mens", "formality": "Casual", "type": "Bottom", "specific_type": "Activewear Pants"},
    "288": {"gender": "Mens", "formality": "Casual", "type": "Bottom", "specific_type": "Activewear Shorts"},
    "289": {"gender": "Mens", "formality": "Casual", "type": "Top", "specific_type": "Activewear Jackets"},
    "309": {"gender": "Unisex", "formality": "Casual", "type": "Top", "specific_type": "Activewear Tank Tops"},
    "310": {"gender": "Both", "formality": "Casual", "type": "Bottom", "specific_type": "Straight Leg Jeans"},
    "332": {"gender": "Both", "formality": "Casual", "type": "Bottom", "specific_type": "Capri & Cropped Pants"},
    "4516": {"gender": "Both", "formality": "Formal", "type": "Top", "specific_type": "Wedding Dresses"},
    "1605": {"gender": "Womens", "formality": "Casual", "type": "Top", "specific_type": "Bikinis"},
    "1606": {"gender": "Womens", "formality": "Casual", "type": "Top", "specific_type": "One Piece Swimsuits"},
    "1607": {"gender": "Womens", "formality": "Casual", "type": "Top", "specific_type": "Cover-ups"}
}"""

